import { PRODUCT_IMAGES } from "../productImages";

/**
 * Accessories — a new category. The shop manager's demo catalog already had an
 * "Accessories" bucket (`DEMO_CATEGORY_TO_ID` mapped it onto `laptops`, for want of anywhere
 * real); this gives it an actual home, and its own `/filter?category=accessories` page.
 */
export const ACCESSORIES = [
  {
    id: "fp-101",
    title: "Logitech MX Master 3S Wireless Mouse Graphite",
    priceValue: 42000,
    image: PRODUCT_IMAGES.mouse,
    categoryId: "accessories",
    brandId: "logitech",
    colorId: "grey",
    screenInch: null,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: 500,
    weightGrams: 141,
    releaseYear: 2022,
    warrantyMonths: 24,
    mpn: "910-006559",
    ratingValue: 4.8,
    reviewCount: 1245,
    homeSection: "variety",
  },
  {
    id: "fp-102",
    title: "Logitech MX Keys S Wireless Keyboard Graphite",
    priceValue: 58000,
    image: PRODUCT_IMAGES.keyboard,
    categoryId: "accessories",
    brandId: "logitech",
    colorId: "grey",
    screenInch: null,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    weightGrams: 810,
    releaseYear: 2023,
    warrantyMonths: 24,
    mpn: "920-011590",
    ratingValue: 4.7,
    reviewCount: 396,
  },
  {
    id: "fp-103",
    title: "Keychron K8 Pro Mechanical Keyboard White",
    priceValue: 65000,
    image: PRODUCT_IMAGES.keyboardWhite,
    categoryId: "accessories",
    brandId: "keychron",
    colorId: "white",
    screenInch: null,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: 4000,
    weightGrams: 918,
    releaseYear: 2022,
    warrantyMonths: 12,
    mpn: "K8PRO-J1",
    ratingValue: 4.6,
    reviewCount: 187,
  },
  {
    id: "fp-104",
    title: "Razer DeathAdder V3 Gaming Mouse Black",
    priceValue: 38000,
    image: PRODUCT_IMAGES.mouseWireless,
    categoryId: "accessories",
    brandId: "razer",
    colorId: "black",
    screenInch: null,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    weightGrams: 59,
    releaseYear: 2022,
    warrantyMonths: 24,
    mpn: "RZ01-04640100",
    ratingValue: 4.7,
    reviewCount: 512,
  },
  {
    id: "fp-105",
    title: "TP-Link Archer AXE75 Wi-Fi 6E Router",
    priceValue: 95000,
    image: PRODUCT_IMAGES.router,
    categoryId: "accessories",
    brandId: "tplink",
    colorId: "black",
    screenInch: null,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    weightGrams: 620,
    releaseYear: 2022,
    warrantyMonths: 24,
    mpn: "ARCHERAXE75",
    ratingValue: 4.5,
    reviewCount: 143,
  },
  {
    id: "fp-106",
    title: "Anker 737 PowerCore 24000mAh Power Bank",
    priceValue: 52000,
    image: PRODUCT_IMAGES.powerBank,
    categoryId: "accessories",
    brandId: "anker",
    colorId: "black",
    screenInch: null,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: 24000,
    weightGrams: 490,
    releaseYear: 2022,
    warrantyMonths: 18,
    mpn: "A1289",
    ratingValue: 4.6,
    reviewCount: 298,
  },
  {
    id: "fp-107",
    title: "Anker Nano Power Bank 10000mAh White",
    priceValue: 24000,
    image: PRODUCT_IMAGES.powerBank,
    categoryId: "accessories",
    brandId: "anker",
    colorId: "white",
    screenInch: null,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: 10000,
    weightGrams: 181,
    releaseYear: 2023,
    warrantyMonths: 18,
    mpn: "A1257",
    ratingValue: 4.5,
    reviewCount: 421,
  },
  {
    id: "fp-108",
    title: "Xiaomi Smart Projector 2 Pro",
    priceValue: 285000,
    image: PRODUCT_IMAGES.projector,
    categoryId: "accessories",
    brandId: "xiaomi",
    colorId: "white",
    screenInch: 120,
    refreshHz: 60,
    storageGb: 16,
    ramGb: 2,
    batteryMah: null,
    weightGrams: 1900,
    releaseYear: 2023,
    warrantyMonths: 12,
    mpn: "MJJGT03YM",
    ratingValue: 4.4,
    reviewCount: 96,
  },
];
