import { PRODUCT_IMAGES } from "../productImages";

/**
 * Cameras and lenses. See `productCatalog.js` for the shape and for why the ids are
 * append-only.
 *
 * `cameraKind` ("lens" | "mirrorless" | "action" | "drone") and `lensAperture` (lenses only)
 * exist because this category is not one kind of product: an interchangeable lens has a
 * fixed maximum aperture worth stating, a mirrorless body does not, and neither fact applies
 * to an action camera or a drone. The extended spec table used to print "f/1.4 aperture" on
 * every product here, including camera bodies and a drone that have no aperture spec at all.
 */
export const CAMERAS = [
  {
    id: "fp-5",
    title: "Sigma 30mm f/1.4 Contemporary DC DN",
    priceValue: 185000,
    image: PRODUCT_IMAGES.lens,
    categoryId: "cameras",
    brandId: "sigma",
    colorId: "black",
    cameraKind: "lens",
    lensAperture: "f/1.4",
    screenInch: null,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    weightGrams: 265,
    releaseYear: 2020,
    warrantyMonths: 24,
    mpn: "302965",
    ratingValue: 4.7,
    reviewCount: 89,
    homeSection: "top",
  },
  {
    id: "fp-85",
    title: "Sony Alpha a6700 Mirrorless Body Black",
    priceValue: 745000,
    image: PRODUCT_IMAGES.cameraSony,
    categoryId: "cameras",
    brandId: "sony",
    colorId: "black",
    cameraKind: "mirrorless",
    lensAperture: null,
    screenInch: 3,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    weightGrams: 493,
    releaseYear: 2023,
    warrantyMonths: 24,
    mpn: "ILCE-6700",
    ratingValue: 4.7,
    reviewCount: 156,
    homeSection: "variety",
  },
  {
    id: "fp-86",
    title: "Canon EOS R50 Mirrorless Kit 18-45mm Black",
    priceValue: 425000,
    image: PRODUCT_IMAGES.cameraCanon,
    categoryId: "cameras",
    brandId: "canon",
    colorId: "black",
    cameraKind: "mirrorless",
    lensAperture: null,
    screenInch: 3,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    weightGrams: 375,
    releaseYear: 2023,
    warrantyMonths: 24,
    mpn: "5811C012",
    ratingValue: 4.6,
    reviewCount: 213,
  },
  {
    id: "fp-87",
    title: "Fujifilm X-T5 Mirrorless Body Silver",
    priceValue: 890000,
    image: PRODUCT_IMAGES.cameraBody,
    categoryId: "cameras",
    brandId: "fujifilm",
    colorId: "silver",
    cameraKind: "mirrorless",
    lensAperture: null,
    screenInch: 3,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    weightGrams: 557,
    releaseYear: 2022,
    warrantyMonths: 24,
    mpn: "16783113",
    ratingValue: 4.8,
    reviewCount: 178,
  },
  {
    id: "fp-88",
    title: "Nikon Z50 II Mirrorless Kit 16-50mm Black",
    priceValue: 495000,
    image: PRODUCT_IMAGES.cameraNikon,
    categoryId: "cameras",
    brandId: "nikon",
    colorId: "black",
    cameraKind: "mirrorless",
    lensAperture: null,
    screenInch: 3.2,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    weightGrams: 550,
    releaseYear: 2024,
    warrantyMonths: 24,
    mpn: "VOA110K001",
    ratingValue: 4.6,
    reviewCount: 92,
  },
  {
    id: "fp-89",
    title: "Sigma 56mm f/1.4 DC DN Contemporary",
    priceValue: 215000,
    image: PRODUCT_IMAGES.lensPortrait,
    categoryId: "cameras",
    brandId: "sigma",
    colorId: "black",
    cameraKind: "lens",
    lensAperture: "f/1.4",
    screenInch: null,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    weightGrams: 280,
    releaseYear: 2019,
    warrantyMonths: 24,
    mpn: "351965",
    ratingValue: 4.7,
    reviewCount: 64,
  },
  {
    id: "fp-90",
    title: "Tamron 17-70mm f/2.8 Di III-A VC RXD",
    priceValue: 265000,
    image: PRODUCT_IMAGES.lensWide,
    categoryId: "cameras",
    brandId: "tamron",
    colorId: "black",
    cameraKind: "lens",
    lensAperture: "f/2.8",
    screenInch: null,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    weightGrams: 525,
    releaseYear: 2021,
    warrantyMonths: 24,
    mpn: "B070",
    ratingValue: 4.6,
    reviewCount: 47,
  },
  {
    id: "fp-91",
    title: "GoPro HERO13 Black Waterproof Action Camera",
    priceValue: 235000,
    image: PRODUCT_IMAGES.actionCamera,
    categoryId: "cameras",
    brandId: "gopro",
    colorId: "black",
    cameraKind: "action",
    lensAperture: null,
    screenInch: 2.27,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    weightGrams: 154,
    releaseYear: 2024,
    warrantyMonths: 12,
    mpn: "CHDHX-131",
    ratingValue: 4.5,
    reviewCount: 267,
  },
  {
    id: "fp-92",
    title: "DJI Mini 4 Pro Drone with RC 2 Remote",
    priceValue: 495000,
    image: PRODUCT_IMAGES.drone,
    categoryId: "cameras",
    brandId: "dji",
    colorId: "grey",
    cameraKind: "drone",
    lensAperture: null,
    screenInch: null,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: 2590,
    weightGrams: 249,
    releaseYear: 2023,
    warrantyMonths: 12,
    mpn: "CP.MA.00000740.01",
    ratingValue: 4.7,
    reviewCount: 154,
  },
];
