import { PRODUCT_IMAGES } from "../productImages";

/**
 * Game consoles and controllers — a new category. The shop manager's demo catalog already
 * had a "Gaming" bucket (`DEMO_CATEGORY_TO_ID` mapped it onto `tv`, for want of anywhere
 * real); this gives it an actual home, and its own `/filter?category=consoles` page.
 */
export const CONSOLES = [
  {
    id: "fp-93",
    title: "Sony PlayStation 5 Pro 2TB",
    priceValue: 495000,
    image: PRODUCT_IMAGES.console,
    categoryId: "consoles",
    brandId: "sony",
    colorId: "white",
    screenInch: null,
    refreshHz: null,
    storageGb: 2000,
    ramGb: 16,
    batteryMah: null,
    weightGrams: 3200,
    releaseYear: 2024,
    warrantyMonths: 12,
    mpn: "CFI-7000B",
    ratingValue: 4.8,
    reviewCount: 421,
    homeSection: "top",
  },
  {
    id: "fp-94",
    title: "Sony PlayStation 5 Slim 1TB",
    priceValue: 345000,
    image: PRODUCT_IMAGES.consoleTv,
    categoryId: "consoles",
    brandId: "sony",
    colorId: "white",
    screenInch: null,
    refreshHz: null,
    storageGb: 1000,
    ramGb: 16,
    batteryMah: null,
    weightGrams: 2600,
    releaseYear: 2023,
    warrantyMonths: 12,
    mpn: "CFI-2000A",
    ratingValue: 4.7,
    reviewCount: 968,
    homeSection: "variety",
  },
  {
    id: "fp-95",
    title: "Microsoft Xbox Series X 1TB",
    priceValue: 335000,
    image: PRODUCT_IMAGES.consoleTv,
    categoryId: "consoles",
    brandId: "microsoft",
    colorId: "black",
    screenInch: null,
    refreshHz: null,
    storageGb: 1000,
    ramGb: 16,
    batteryMah: null,
    weightGrams: 4450,
    releaseYear: 2020,
    warrantyMonths: 12,
    mpn: "RRT-00009",
    ratingValue: 4.6,
    reviewCount: 743,
  },
  {
    id: "fp-96",
    title: "Microsoft Xbox Series S 512GB",
    priceValue: 165000,
    image: PRODUCT_IMAGES.consoleRetro,
    categoryId: "consoles",
    brandId: "microsoft",
    colorId: "white",
    screenInch: null,
    refreshHz: null,
    storageGb: 512,
    ramGb: 10,
    batteryMah: null,
    weightGrams: 1930,
    releaseYear: 2020,
    warrantyMonths: 12,
    mpn: "RRS-00007",
    ratingValue: 4.4,
    reviewCount: 512,
  },
  {
    id: "fp-97",
    title: "Nintendo Switch 2 256GB",
    priceValue: 265000,
    image: PRODUCT_IMAGES.consoleRetro,
    categoryId: "consoles",
    brandId: "nintendo",
    colorId: "black",
    screenInch: 7.9,
    refreshHz: 120,
    storageGb: 256,
    ramGb: 12,
    batteryMah: 5220,
    weightGrams: 401,
    releaseYear: 2025,
    warrantyMonths: 12,
    mpn: "HEG-001",
    ratingValue: 4.8,
    reviewCount: 267,
  },
  {
    id: "fp-98",
    title: "Sony DualSense Wireless Controller White",
    priceValue: 42000,
    image: PRODUCT_IMAGES.controllerWhite,
    categoryId: "consoles",
    brandId: "sony",
    colorId: "white",
    screenInch: null,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: 1560,
    weightGrams: 280,
    releaseYear: 2020,
    warrantyMonths: 12,
    mpn: "CFI-ZCT1W",
    ratingValue: 4.6,
    reviewCount: 891,
  },
  {
    id: "fp-99",
    title: "Microsoft Xbox Wireless Controller Black",
    priceValue: 38000,
    image: PRODUCT_IMAGES.controllerXbox,
    categoryId: "consoles",
    brandId: "microsoft",
    colorId: "black",
    screenInch: null,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    weightGrams: 287,
    releaseYear: 2020,
    warrantyMonths: 12,
    mpn: "QAT-00001",
    ratingValue: 4.7,
    reviewCount: 634,
  },
  {
    id: "fp-100",
    title: "Meta Quest 3 128GB VR Headset",
    priceValue: 375000,
    image: PRODUCT_IMAGES.vrHeadset,
    categoryId: "consoles",
    brandId: "meta",
    colorId: "white",
    screenInch: null,
    refreshHz: 120,
    storageGb: 128,
    ramGb: 8,
    batteryMah: 5000,
    weightGrams: 515,
    releaseYear: 2023,
    warrantyMonths: 12,
    mpn: "899-00587-01",
    ratingValue: 4.5,
    reviewCount: 178,
  },
];
