import { PRODUCT_IMAGES } from "../productImages";

/**
 * Headphones and earbuds. See `productCatalog.js` for the shape and for why the ids are
 * append-only. No `screenInch`/`storageGb`: neither field applies to audio, and the specs
 * builder and variant builder both already treat their absence as "this product has none".
 */
export const HEADPHONES = [
  {
    id: "fp-3",
    title: "Sony WH-1000XM5 Wireless Headphones",
    priceValue: 165000,
    image: PRODUCT_IMAGES.headphones,
    categoryId: "headphones",
    brandId: "sony",
    colorId: "white",
    screenInch: null,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    batteryHours: 30,
    weightGrams: 250,
    releaseYear: 2022,
    warrantyMonths: 24,
    mpn: "WH1000XM5",
    ratingValue: 4.8,
    reviewCount: 927,
    homeSection: "top",
  },
  {
    id: "fp-12",
    title: "Apple AirPods Pro 2 USB-C",
    priceValue: 129000,
    image: PRODUCT_IMAGES.earbuds,
    categoryId: "headphones",
    brandId: "apple",
    colorId: "white",
    screenInch: null,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    batteryHours: 6,
    weightGrams: 5,
    releaseYear: 2023,
    warrantyMonths: 12,
    mpn: "MTJV3",
    ratingValue: 4.7,
    reviewCount: 1523,
    homeSection: "variety",
  },
  {
    id: "fp-21",
    title: "Sony WF-1000XM5 Wireless Earbuds",
    priceValue: 118000,
    image: PRODUCT_IMAGES.earbuds,
    categoryId: "headphones",
    brandId: "sony",
    colorId: "black",
    screenInch: null,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    batteryHours: 8,
    weightGrams: 6,
    releaseYear: 2023,
    warrantyMonths: 24,
    mpn: "WF1000XM5",
    ratingValue: 4.7,
    reviewCount: 412,
  },
  {
    id: "fp-69",
    title: "Bose QuietComfort Ultra Headphones Black",
    priceValue: 175000,
    image: PRODUCT_IMAGES.headphonesBlack,
    categoryId: "headphones",
    brandId: "bose",
    colorId: "black",
    screenInch: null,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    batteryHours: 24,
    weightGrams: 254,
    releaseYear: 2023,
    warrantyMonths: 24,
    mpn: "882826-0010",
    ratingValue: 4.6,
    reviewCount: 341,
    homeSection: "top",
  },
  {
    id: "fp-70",
    title: "Bose QuietComfort Earbuds II White",
    priceValue: 135000,
    image: PRODUCT_IMAGES.earbudsWhite,
    categoryId: "headphones",
    brandId: "bose",
    colorId: "white",
    screenInch: null,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    batteryHours: 6,
    weightGrams: 6,
    releaseYear: 2022,
    warrantyMonths: 24,
    mpn: "870730-0020",
    ratingValue: 4.5,
    reviewCount: 189,
  },
  {
    id: "fp-71",
    title: "Sennheiser Momentum 4 Wireless Black",
    priceValue: 155000,
    image: PRODUCT_IMAGES.headphonesSilver,
    categoryId: "headphones",
    brandId: "sennheiser",
    colorId: "black",
    screenInch: null,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    batteryHours: 60,
    weightGrams: 293,
    releaseYear: 2022,
    warrantyMonths: 24,
    mpn: "M4AEBT2BLK",
    ratingValue: 4.6,
    reviewCount: 156,
  },
  {
    id: "fp-72",
    title: "JBL Tune 770NC Wireless Headphones Blue",
    priceValue: 62000,
    image: PRODUCT_IMAGES.headphonesPink,
    categoryId: "headphones",
    brandId: "jbl",
    colorId: "blue",
    screenInch: null,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    batteryHours: 44,
    weightGrams: 220,
    releaseYear: 2023,
    warrantyMonths: 12,
    mpn: "JBLT770NCBLU",
    ratingValue: 4.3,
    reviewCount: 267,
  },
  {
    id: "fp-73",
    title: "Xiaomi Buds 5 Pro Black",
    priceValue: 58000,
    image: PRODUCT_IMAGES.earbudsBlue,
    categoryId: "headphones",
    brandId: "xiaomi",
    colorId: "black",
    screenInch: null,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    batteryHours: 9,
    weightGrams: 6,
    releaseYear: 2024,
    warrantyMonths: 12,
    mpn: "BHR7994GL",
    ratingValue: 4.3,
    reviewCount: 198,
  },
  {
    id: "fp-74",
    title: "Marshall Major V Bluetooth Headphones Black",
    priceValue: 68000,
    image: PRODUCT_IMAGES.headphonesBlack,
    categoryId: "headphones",
    brandId: "marshall",
    colorId: "black",
    screenInch: null,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    batteryHours: 100,
    weightGrams: 165,
    releaseYear: 2023,
    warrantyMonths: 24,
    mpn: "1006086",
    ratingValue: 4.5,
    reviewCount: 143,
  },
];
