import { PRODUCT_IMAGES } from "../productImages";

/** Laptops. See `productCatalog.js` for the shape and for why the ids are append-only. */
export const LAPTOPS = [
  {
    id: "fp-2",
    title: "Apple MacBook Pro 14 M4 Pro 512GB Space Black",
    priceValue: 1290000,
    image: PRODUCT_IMAGES.macbook,
    categoryId: "laptops",
    brandId: "apple",
    colorId: "black",
    screenInch: 14.2,
    refreshHz: 120,
    storageGb: 512,
    ramGb: 24,
    batteryMah: null,
    weightGrams: 1600,
    releaseYear: 2024,
    warrantyMonths: 12,
    mpn: "MX2E3",
    ratingValue: 4.9,
    reviewCount: 612,
    homeSection: "top",
  },
  {
    id: "fp-7",
    title: "Dell XPS 15 OLED 1TB Silver",
    priceValue: 1080000,
    image: PRODUCT_IMAGES.laptop,
    categoryId: "laptops",
    brandId: "dell",
    colorId: "silver",
    screenInch: 15.6,
    refreshHz: 60,
    storageGb: 1000,
    ramGb: 32,
    batteryMah: null,
    weightGrams: 1840,
    releaseYear: 2024,
    warrantyMonths: 24,
    mpn: "XPS9530",
    ratingValue: 4.6,
    reviewCount: 341,
  },
  {
    id: "fp-8",
    title: "HP Spectre x360 14 OLED",
    priceValue: 760000,
    image: PRODUCT_IMAGES.laptop,
    categoryId: "laptops",
    brandId: "hp",
    colorId: "navy",
    screenInch: 14,
    refreshHz: 60,
    storageGb: 512,
    ramGb: 16,
    batteryMah: null,
    weightGrams: 1360,
    releaseYear: 2024,
    warrantyMonths: 24,
    mpn: "SPX360-14",
    ratingValue: 4.5,
    reviewCount: 198,
  },
  {
    id: "fp-9",
    title: "Lenovo ThinkPad X1 Carbon Gen 12",
    priceValue: 950000,
    image: PRODUCT_IMAGES.laptop,
    categoryId: "laptops",
    brandId: "lenovo",
    colorId: "black",
    screenInch: 14,
    refreshHz: 60,
    storageGb: 512,
    ramGb: 16,
    batteryMah: null,
    weightGrams: 1120,
    releaseYear: 2024,
    warrantyMonths: 36,
    mpn: "21KC001",
    ratingValue: 4.7,
    reviewCount: 289,
  },
  {
    id: "fp-14",
    title: "Apple MacBook Air 13 M3 256GB Midnight",
    priceValue: 690000,
    image: PRODUCT_IMAGES.macbook,
    categoryId: "laptops",
    brandId: "apple",
    colorId: "black",
    screenInch: 13.6,
    refreshHz: 60,
    storageGb: 256,
    ramGb: 8,
    batteryMah: null,
    weightGrams: 1240,
    releaseYear: 2024,
    warrantyMonths: 12,
    mpn: "MRXV3",
    ratingValue: 4.8,
    reviewCount: 1042,
    homeSection: "variety",
  },
  {
    id: "fp-15",
    title: "Samsung Galaxy Book4 Pro 16",
    priceValue: 880000,
    image: PRODUCT_IMAGES.laptop,
    categoryId: "laptops",
    brandId: "samsung",
    colorId: "black",
    screenInch: 16,
    refreshHz: 120,
    storageGb: 512,
    ramGb: 16,
    batteryMah: null,
    weightGrams: 1560,
    releaseYear: 2024,
    warrantyMonths: 24,
    mpn: "NP960XGL",
    ratingValue: 4.4,
    reviewCount: 156,
  },
  {
    id: "fp-17",
    title: "Dell Latitude 7450 Business Laptop",
    priceValue: 640000,
    image: PRODUCT_IMAGES.laptop,
    categoryId: "laptops",
    brandId: "dell",
    colorId: "black",
    screenInch: 14,
    refreshHz: 60,
    storageGb: 512,
    ramGb: 16,
    batteryMah: null,
    weightGrams: 1360,
    releaseYear: 2024,
    warrantyMonths: 36,
    mpn: "LAT7450",
    ratingValue: 4.4,
    reviewCount: 87,
  },
  {
    id: "fp-18",
    title: "HP Omen 16 RTX Gaming Laptop",
    priceValue: 820000,
    image: PRODUCT_IMAGES.gamingLaptop,
    categoryId: "laptops",
    brandId: "hp",
    colorId: "black",
    screenInch: 16,
    refreshHz: 165,
    storageGb: 1000,
    ramGb: 16,
    batteryMah: null,
    weightGrams: 2460,
    releaseYear: 2024,
    warrantyMonths: 24,
    mpn: "OMEN16-XF",
    ratingValue: 4.5,
    reviewCount: 231,
  },
  {
    id: "fp-19",
    title: "Lenovo Yoga Slim 7 14 OLED",
    priceValue: 590000,
    image: PRODUCT_IMAGES.laptop,
    categoryId: "laptops",
    brandId: "lenovo",
    colorId: "grey",
    screenInch: 14,
    refreshHz: 90,
    storageGb: 512,
    ramGb: 16,
    batteryMah: null,
    weightGrams: 1380,
    releaseYear: 2024,
    warrantyMonths: 24,
    mpn: "82Y30003",
    ratingValue: 4.5,
    reviewCount: 143,
  },
  {
    id: "fp-22",
    title: "Dell Precision 5690 Workstation",
    priceValue: 1420000,
    image: PRODUCT_IMAGES.laptop,
    categoryId: "laptops",
    brandId: "dell",
    colorId: "black",
    screenInch: 16,
    refreshHz: 60,
    storageGb: 1000,
    ramGb: 64,
    batteryMah: null,
    weightGrams: 2130,
    releaseYear: 2024,
    warrantyMonths: 36,
    mpn: "PREC5690",
    ratingValue: 4.6,
    reviewCount: 64,
  },
  {
    id: "fp-23",
    title: "HP Chromebook Plus 14",
    priceValue: 245000,
    image: PRODUCT_IMAGES.laptop,
    categoryId: "laptops",
    brandId: "hp",
    colorId: "grey",
    screenInch: 14,
    refreshHz: 60,
    storageGb: 128,
    ramGb: 8,
    batteryMah: null,
    weightGrams: 1500,
    releaseYear: 2024,
    warrantyMonths: 12,
    mpn: "CB-PLUS14",
    ratingValue: 4.2,
    reviewCount: 176,
  },
  {
    id: "fp-24",
    title: "Lenovo Legion 15",
    priceValue: 890000,
    image: PRODUCT_IMAGES.gamingLaptop,
    categoryId: "laptops",
    brandId: "lenovo",
    colorId: "black",
    screenInch: 15.6,
    refreshHz: 165,
    storageGb: 512,
    ramGb: 16,
    batteryMah: null,
    weightGrams: 2400,
    releaseYear: 2024,
    warrantyMonths: 24,
    mpn: "82Y50003",
    ratingValue: 4.5,
    reviewCount: 203,
  },
  {
    id: "fp-26",
    title: "Lenovo Legion 5 16-inch RTX Gaming Laptop",
    priceValue: 790000,
    image: PRODUCT_IMAGES.gamingLaptop,
    categoryId: "laptops",
    brandId: "lenovo",
    colorId: "black",
    screenInch: 16,
    refreshHz: 165,
    storageGb: 1000,
    ramGb: 16,
    batteryMah: null,
    weightGrams: 2450,
    releaseYear: 2024,
    warrantyMonths: 24,
    mpn: "82Y70003",
    ratingValue: 4.6,
    reviewCount: 318,
    homeSection: "variety",
  },
  {
    id: "fp-45",
    title: "ASUS ROG Zephyrus G14 RTX 4070 1TB Eclipse Gray",
    priceValue: 970000,
    image: PRODUCT_IMAGES.asusLaptop,
    categoryId: "laptops",
    brandId: "asus",
    colorId: "grey",
    screenInch: 14,
    refreshHz: 165,
    storageGb: 1000,
    ramGb: 32,
    batteryMah: null,
    weightGrams: 1650,
    releaseYear: 2025,
    warrantyMonths: 24,
    mpn: "GA403UI",
    ratingValue: 4.7,
    reviewCount: 224,
  },
  {
    id: "fp-46",
    title: "ASUS Zenbook 14 OLED 512GB Ponder Blue",
    priceValue: 545000,
    image: PRODUCT_IMAGES.laptopSilver,
    categoryId: "laptops",
    brandId: "asus",
    colorId: "blue",
    screenInch: 14,
    refreshHz: 120,
    storageGb: 512,
    ramGb: 16,
    batteryMah: null,
    weightGrams: 1200,
    releaseYear: 2024,
    warrantyMonths: 24,
    mpn: "UX3405MA",
    ratingValue: 4.5,
    reviewCount: 179,
  },
  {
    id: "fp-47",
    title: "ASUS Vivobook Go 15 256GB Cool Silver",
    priceValue: 295000,
    image: PRODUCT_IMAGES.laptopSilver,
    categoryId: "laptops",
    brandId: "asus",
    colorId: "silver",
    screenInch: 15.6,
    refreshHz: 60,
    storageGb: 256,
    ramGb: 8,
    batteryMah: null,
    weightGrams: 1630,
    releaseYear: 2024,
    warrantyMonths: 24,
    mpn: "E1504FA",
    ratingValue: 4.2,
    reviewCount: 267,
  },
  {
    id: "fp-48",
    title: "Acer Swift Go 14 OLED 512GB Pure Silver",
    priceValue: 460000,
    image: PRODUCT_IMAGES.acerLaptop,
    categoryId: "laptops",
    brandId: "acer",
    colorId: "silver",
    screenInch: 14,
    refreshHz: 90,
    storageGb: 512,
    ramGb: 16,
    batteryMah: null,
    weightGrams: 1280,
    releaseYear: 2024,
    warrantyMonths: 24,
    mpn: "SFG14-72",
    ratingValue: 4.4,
    reviewCount: 132,
  },
  {
    id: "fp-49",
    title: "Acer Predator Helios Neo 16 RTX 4060 1TB Black",
    priceValue: 940000,
    image: PRODUCT_IMAGES.gamingLaptopDesk,
    categoryId: "laptops",
    brandId: "acer",
    colorId: "black",
    screenInch: 16,
    refreshHz: 165,
    storageGb: 1000,
    ramGb: 16,
    batteryMah: null,
    weightGrams: 2600,
    releaseYear: 2024,
    warrantyMonths: 24,
    mpn: "PHN16-72",
    ratingValue: 4.5,
    reviewCount: 158,
  },
  {
    id: "fp-50",
    title: "MSI Katana 15 RTX 4070 1TB Black",
    priceValue: 860000,
    image: PRODUCT_IMAGES.gamingLaptopDesk,
    categoryId: "laptops",
    brandId: "msi",
    colorId: "black",
    screenInch: 15.6,
    refreshHz: 144,
    storageGb: 1000,
    ramGb: 16,
    batteryMah: null,
    weightGrams: 2250,
    releaseYear: 2024,
    warrantyMonths: 24,
    mpn: "KATANA15B13V",
    ratingValue: 4.4,
    reviewCount: 96,
  },
  {
    id: "fp-51",
    title: "Microsoft Surface Laptop 7 512GB Sapphire",
    priceValue: 780000,
    image: PRODUCT_IMAGES.laptopSilver,
    categoryId: "laptops",
    brandId: "microsoft",
    colorId: "blue",
    screenInch: 13.8,
    refreshHz: 120,
    storageGb: 512,
    ramGb: 16,
    batteryMah: null,
    weightGrams: 1340,
    releaseYear: 2024,
    warrantyMonths: 24,
    mpn: "ZGV-00046",
    ratingValue: 4.6,
    reviewCount: 121,
  },
];
