import { PRODUCT_IMAGES } from "../productImages";

/**
 * Monitors — a new category (the catalog had none). See `productCatalog.js` for the shape.
 * No `storageGb`/`batteryMah`: a monitor has neither, and `buildSpecsForProduct` /
 * `buildVariantsForProduct` already drop rows a product has no value for.
 *
 * `panelType` is the real panel technology (see the same field on `tv.js` for why it isn't
 * a single literal shared by the category — an OLED gaming monitor and an IPS productivity
 * monitor are not the same panel just because both show up under "Monitors").
 */
export const MONITORS = [
  {
    id: "fp-57",
    title: "Dell UltraSharp U2723QE 27-inch 4K Monitor",
    priceValue: 315000,
    image: PRODUCT_IMAGES.monitor,
    categoryId: "monitors",
    brandId: "dell",
    colorId: "black",
    panelType: "IPS Black",
    screenInch: 27,
    refreshHz: 60,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    weightGrams: 6200,
    releaseYear: 2023,
    warrantyMonths: 36,
    mpn: "U2723QE",
    ratingValue: 4.7,
    reviewCount: 214,
  },
  {
    id: "fp-58",
    title: "LG UltraGear 27GR95QE 27-inch QHD 240Hz Monitor",
    priceValue: 385000,
    image: PRODUCT_IMAGES.monitorDual,
    categoryId: "monitors",
    brandId: "lg",
    colorId: "black",
    panelType: "QD-OLED",
    screenInch: 27,
    refreshHz: 240,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    weightGrams: 6700,
    releaseYear: 2023,
    warrantyMonths: 24,
    mpn: "27GR95QE",
    ratingValue: 4.6,
    reviewCount: 132,
    homeSection: "variety",
  },
  {
    id: "fp-59",
    title: "Samsung Odyssey G9 49-inch Curved Monitor",
    priceValue: 620000,
    image: PRODUCT_IMAGES.monitorWhite,
    categoryId: "monitors",
    brandId: "samsung",
    colorId: "white",
    panelType: "VA",
    screenInch: 49,
    refreshHz: 240,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    weightGrams: 14400,
    releaseYear: 2023,
    warrantyMonths: 24,
    mpn: "LS49CG954SUXEN",
    ratingValue: 4.5,
    reviewCount: 87,
  },
  {
    id: "fp-60",
    title: "ASUS ProArt PA278CV 27-inch QHD Monitor",
    priceValue: 225000,
    image: PRODUCT_IMAGES.monitorDesk,
    categoryId: "monitors",
    brandId: "asus",
    colorId: "black",
    panelType: "IPS",
    screenInch: 27,
    refreshHz: 75,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    weightGrams: 5300,
    releaseYear: 2022,
    warrantyMonths: 36,
    mpn: "PA278CV",
    ratingValue: 4.5,
    reviewCount: 96,
  },
  {
    id: "fp-61",
    title: "Apple Studio Display 27-inch 5K Retina",
    priceValue: 890000,
    image: PRODUCT_IMAGES.monitorWhite,
    categoryId: "monitors",
    brandId: "apple",
    colorId: "silver",
    panelType: "IPS Retina",
    screenInch: 27,
    refreshHz: 60,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    weightGrams: 6300,
    releaseYear: 2022,
    warrantyMonths: 12,
    mpn: "MMYQ3",
    ratingValue: 4.6,
    reviewCount: 178,
  },
];
