import { PRODUCT_IMAGES } from "../productImages";

/**
 * Smartphones. See `productCatalog.js` for the shape and for why the ids are append-only.
 *
 * `refreshHz` is stated even when it is 60: a 60 Hz panel on a 2025 phone is a real fact a
 * shopper compares, and omitting it would make the spec row disappear rather than read "60 Hz".
 */
export const SMARTPHONES = [
  {
    id: "fp-1",
    title: "Apple iPhone 17 Pro Max 256GB Cosmic Orange",
    priceValue: 739000,
    image: PRODUCT_IMAGES.iphoneOrange,
    categoryId: "smartphones",
    brandId: "apple",
    colorId: "orange",
    screenInch: 6.9,
    refreshHz: 120,
    storageGb: 256,
    ramGb: 12,
    batteryMah: 4832,
    weightGrams: 233,
    releaseYear: 2025,
    warrantyMonths: 12,
    mpn: "MYWK3",
    ratingValue: 4.8,
    reviewCount: 486,
    homeSection: "top",
  },
  {
    id: "fp-4",
    title: "Samsung Galaxy S25 Ultra 512GB Titanium Black",
    priceValue: 615000,
    image: PRODUCT_IMAGES.samsungPhone,
    categoryId: "smartphones",
    brandId: "samsung",
    colorId: "black",
    screenInch: 6.9,
    refreshHz: 120,
    storageGb: 512,
    ramGb: 12,
    batteryMah: 5000,
    weightGrams: 218,
    releaseYear: 2025,
    warrantyMonths: 24,
    mpn: "SM-S938B",
    ratingValue: 4.7,
    reviewCount: 731,
    homeSection: "top",
  },
  {
    id: "fp-16",
    title: "Apple iPhone 16 128GB Ultramarine",
    priceValue: 445000,
    image: PRODUCT_IMAGES.iphoneBlack,
    categoryId: "smartphones",
    brandId: "apple",
    colorId: "blue",
    screenInch: 6.1,
    refreshHz: 60,
    storageGb: 128,
    ramGb: 8,
    batteryMah: 3561,
    weightGrams: 170,
    releaseYear: 2024,
    warrantyMonths: 12,
    mpn: "MYEG3",
    ratingValue: 4.7,
    reviewCount: 1284,
  },
  {
    id: "fp-20",
    title: "Samsung Galaxy S24 FE 256GB Graphite",
    priceValue: 335000,
    image: PRODUCT_IMAGES.samsungPhone,
    categoryId: "smartphones",
    brandId: "samsung",
    colorId: "black",
    screenInch: 6.7,
    refreshHz: 120,
    storageGb: 256,
    ramGb: 8,
    batteryMah: 4700,
    weightGrams: 213,
    releaseYear: 2024,
    warrantyMonths: 24,
    mpn: "SM-S721B",
    ratingValue: 4.5,
    reviewCount: 542,
  },
  {
    id: "fp-25",
    title: "Apple iPhone 17 Pro 128GB Natural Titanium",
    priceValue: 629000,
    image: PRODUCT_IMAGES.iphoneOrange,
    categoryId: "smartphones",
    brandId: "apple",
    colorId: "white",
    screenInch: 6.3,
    refreshHz: 120,
    storageGb: 128,
    ramGb: 12,
    batteryMah: 3650,
    weightGrams: 199,
    releaseYear: 2025,
    warrantyMonths: 12,
    mpn: "MYNJ3",
    ratingValue: 4.8,
    reviewCount: 397,
    homeSection: "variety",
  },
  {
    id: "fp-28",
    title: "Apple iPhone 17 256GB Lavender",
    priceValue: 519000,
    image: PRODUCT_IMAGES.phoneWhite,
    categoryId: "smartphones",
    brandId: "apple",
    colorId: "purple",
    screenInch: 6.3,
    refreshHz: 120,
    storageGb: 256,
    ramGb: 8,
    batteryMah: 3692,
    weightGrams: 177,
    releaseYear: 2025,
    warrantyMonths: 12,
    mpn: "MG0X4",
    ratingValue: 4.7,
    reviewCount: 268,
  },
  {
    id: "fp-29",
    title: "Apple iPhone 16 Pro 256GB Desert Titanium",
    priceValue: 585000,
    image: PRODUCT_IMAGES.phoneSilver,
    categoryId: "smartphones",
    brandId: "apple",
    colorId: "beige",
    screenInch: 6.3,
    refreshHz: 120,
    storageGb: 256,
    ramGb: 8,
    batteryMah: 3582,
    weightGrams: 199,
    releaseYear: 2024,
    warrantyMonths: 12,
    mpn: "MYNK3",
    ratingValue: 4.8,
    reviewCount: 934,
  },
  {
    id: "fp-30",
    title: "Apple iPhone 15 128GB Black",
    priceValue: 365000,
    image: PRODUCT_IMAGES.phoneOnBlack,
    categoryId: "smartphones",
    brandId: "apple",
    colorId: "black",
    screenInch: 6.1,
    refreshHz: 60,
    storageGb: 128,
    ramGb: 6,
    batteryMah: 3349,
    weightGrams: 171,
    releaseYear: 2023,
    warrantyMonths: 12,
    mpn: "MTP03",
    ratingValue: 4.6,
    reviewCount: 1487,
  },
  {
    id: "fp-31",
    title: "Samsung Galaxy S25 256GB Icyblue",
    priceValue: 425000,
    image: PRODUCT_IMAGES.phoneColorRow,
    categoryId: "smartphones",
    brandId: "samsung",
    colorId: "blue",
    screenInch: 6.2,
    refreshHz: 120,
    storageGb: 256,
    ramGb: 12,
    batteryMah: 4000,
    weightGrams: 162,
    releaseYear: 2025,
    warrantyMonths: 24,
    mpn: "SM-S931B",
    ratingValue: 4.6,
    reviewCount: 512,
    homeSection: "top",
  },
  {
    id: "fp-32",
    title: "Samsung Galaxy S25 Plus 512GB Navy",
    priceValue: 545000,
    image: PRODUCT_IMAGES.samsungPhone,
    categoryId: "smartphones",
    brandId: "samsung",
    colorId: "navy",
    screenInch: 6.7,
    refreshHz: 120,
    storageGb: 512,
    ramGb: 12,
    batteryMah: 4900,
    weightGrams: 190,
    releaseYear: 2025,
    warrantyMonths: 24,
    mpn: "SM-S936B",
    ratingValue: 4.7,
    reviewCount: 288,
  },
  {
    id: "fp-33",
    title: "Samsung Galaxy Z Flip7 256GB Coralred",
    priceValue: 640000,
    image: PRODUCT_IMAGES.phoneOnDesk,
    categoryId: "smartphones",
    brandId: "samsung",
    colorId: "red",
    screenInch: 6.9,
    refreshHz: 120,
    storageGb: 256,
    ramGb: 12,
    batteryMah: 4300,
    weightGrams: 188,
    releaseYear: 2025,
    warrantyMonths: 24,
    mpn: "SM-F766B",
    ratingValue: 4.4,
    reviewCount: 176,
  },
  {
    id: "fp-34",
    title: "Samsung Galaxy A56 128GB Awesome Graphite",
    priceValue: 175000,
    image: PRODUCT_IMAGES.androidPhone,
    categoryId: "smartphones",
    brandId: "samsung",
    colorId: "grey",
    screenInch: 6.7,
    refreshHz: 120,
    storageGb: 128,
    ramGb: 8,
    batteryMah: 5000,
    weightGrams: 198,
    releaseYear: 2025,
    warrantyMonths: 24,
    mpn: "SM-A566B",
    ratingValue: 4.5,
    reviewCount: 843,
  },
  {
    id: "fp-35",
    title: "Samsung Galaxy A36 128GB Awesome Lavender",
    priceValue: 135000,
    image: PRODUCT_IMAGES.phoneWhite,
    categoryId: "smartphones",
    brandId: "samsung",
    colorId: "purple",
    screenInch: 6.7,
    refreshHz: 120,
    storageGb: 128,
    ramGb: 6,
    batteryMah: 5000,
    weightGrams: 195,
    releaseYear: 2025,
    warrantyMonths: 24,
    mpn: "SM-A366B",
    ratingValue: 4.3,
    reviewCount: 421,
  },
  {
    id: "fp-36",
    title: "Google Pixel 10 Pro 256GB Obsidian",
    priceValue: 495000,
    image: PRODUCT_IMAGES.pixelPhone,
    categoryId: "smartphones",
    brandId: "google",
    colorId: "black",
    screenInch: 6.3,
    refreshHz: 120,
    storageGb: 256,
    ramGb: 16,
    batteryMah: 4870,
    weightGrams: 207,
    releaseYear: 2025,
    warrantyMonths: 24,
    mpn: "GA05932",
    ratingValue: 4.7,
    reviewCount: 233,
    homeSection: "variety",
  },
  {
    id: "fp-37",
    title: "Google Pixel 10 128GB Frost",
    priceValue: 375000,
    image: PRODUCT_IMAGES.pixelPhone,
    categoryId: "smartphones",
    brandId: "google",
    colorId: "white",
    screenInch: 6.3,
    refreshHz: 120,
    storageGb: 128,
    ramGb: 12,
    batteryMah: 4970,
    weightGrams: 204,
    releaseYear: 2025,
    warrantyMonths: 24,
    mpn: "GA07421",
    ratingValue: 4.6,
    reviewCount: 187,
  },
  {
    id: "fp-38",
    title: "Google Pixel 9a 128GB Iris",
    priceValue: 245000,
    image: PRODUCT_IMAGES.androidPhone,
    categoryId: "smartphones",
    brandId: "google",
    colorId: "purple",
    screenInch: 6.3,
    refreshHz: 120,
    storageGb: 128,
    ramGb: 8,
    batteryMah: 5100,
    weightGrams: 186,
    releaseYear: 2025,
    warrantyMonths: 24,
    mpn: "GA06239",
    ratingValue: 4.5,
    reviewCount: 312,
  },
  {
    id: "fp-39",
    title: "Xiaomi 15 Ultra 512GB Black",
    priceValue: 520000,
    image: PRODUCT_IMAGES.phoneOnBlack,
    categoryId: "smartphones",
    brandId: "xiaomi",
    colorId: "black",
    screenInch: 6.7,
    refreshHz: 120,
    storageGb: 512,
    ramGb: 16,
    batteryMah: 5410,
    weightGrams: 226,
    releaseYear: 2025,
    warrantyMonths: 24,
    mpn: "24122RKC5G",
    ratingValue: 4.6,
    reviewCount: 271,
  },
  {
    id: "fp-40",
    title: "Xiaomi 15 256GB Green",
    priceValue: 335000,
    image: PRODUCT_IMAGES.phoneColorRow,
    categoryId: "smartphones",
    brandId: "xiaomi",
    colorId: "green",
    screenInch: 6.4,
    refreshHz: 120,
    storageGb: 256,
    ramGb: 12,
    batteryMah: 5240,
    weightGrams: 191,
    releaseYear: 2025,
    warrantyMonths: 24,
    mpn: "24031PN0DC",
    ratingValue: 4.5,
    reviewCount: 358,
  },
  {
    id: "fp-41",
    title: "Xiaomi Redmi Note 14 Pro 256GB Ocean Blue",
    priceValue: 145000,
    image: PRODUCT_IMAGES.androidPhone,
    categoryId: "smartphones",
    brandId: "xiaomi",
    colorId: "blue",
    screenInch: 6.7,
    refreshHz: 120,
    storageGb: 256,
    ramGb: 8,
    batteryMah: 5500,
    weightGrams: 190,
    releaseYear: 2024,
    warrantyMonths: 24,
    mpn: "2412DRN4CG",
    ratingValue: 4.4,
    reviewCount: 967,
    homeSection: "variety",
  },
  {
    id: "fp-42",
    title: "Nothing Phone (3) 256GB White",
    priceValue: 265000,
    image: PRODUCT_IMAGES.phoneWhite,
    categoryId: "smartphones",
    brandId: "nothing",
    colorId: "white",
    screenInch: 6.7,
    refreshHz: 120,
    storageGb: 256,
    ramGb: 12,
    batteryMah: 5150,
    weightGrams: 218,
    releaseYear: 2025,
    warrantyMonths: 24,
    mpn: "A059",
    ratingValue: 4.4,
    reviewCount: 154,
  },
  {
    id: "fp-43",
    title: "Honor Magic7 Lite 256GB Titanium Black",
    priceValue: 165000,
    image: PRODUCT_IMAGES.phoneOnBlack,
    categoryId: "smartphones",
    brandId: "honor",
    colorId: "black",
    screenInch: 6.8,
    refreshHz: 120,
    storageGb: 256,
    ramGb: 8,
    batteryMah: 6600,
    weightGrams: 189,
    releaseYear: 2025,
    warrantyMonths: 24,
    mpn: "CRT-NX1",
    ratingValue: 4.3,
    reviewCount: 208,
  },
  {
    id: "fp-44",
    title: "Apple iPhone 16e 128GB White",
    priceValue: 295000,
    image: PRODUCT_IMAGES.phoneSilver,
    categoryId: "smartphones",
    brandId: "apple",
    colorId: "white",
    screenInch: 6.1,
    refreshHz: 60,
    storageGb: 128,
    ramGb: 8,
    batteryMah: 4005,
    weightGrams: 167,
    releaseYear: 2025,
    warrantyMonths: 12,
    mpn: "MXFH3",
    ratingValue: 4.4,
    reviewCount: 129,
  },
];
