import { PRODUCT_IMAGES } from "../productImages";

/** Portable speakers. See `productCatalog.js` for the shape and for why the ids are append-only. */
export const SPEAKERS = [
  {
    id: "fp-27",
    title: "Sony SRS-XG500 Portable Bluetooth Speaker",
    priceValue: 249000,
    image: PRODUCT_IMAGES.speaker,
    categoryId: "speakers",
    brandId: "sony",
    colorId: "black",
    screenInch: null,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    batteryHours: 30,
    weightGrams: 3400,
    releaseYear: 2022,
    warrantyMonths: 24,
    mpn: "SRSXG500",
    ratingValue: 4.6,
    reviewCount: 213,
  },
  {
    id: "fp-75",
    title: "JBL Charge 5 Portable Bluetooth Speaker Red",
    priceValue: 95000,
    image: PRODUCT_IMAGES.speakerRed,
    categoryId: "speakers",
    brandId: "jbl",
    colorId: "red",
    screenInch: null,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    batteryHours: 20,
    weightGrams: 960,
    releaseYear: 2021,
    warrantyMonths: 12,
    mpn: "JBLCHARGE5RED",
    ratingValue: 4.7,
    reviewCount: 541,
    homeSection: "top",
  },
  {
    id: "fp-76",
    title: "JBL Flip 6 Portable Bluetooth Speaker Black",
    priceValue: 62000,
    image: PRODUCT_IMAGES.speakerClip,
    categoryId: "speakers",
    brandId: "jbl",
    colorId: "black",
    screenInch: null,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    batteryHours: 12,
    weightGrams: 550,
    releaseYear: 2021,
    warrantyMonths: 12,
    mpn: "JBLFLIP6BLK",
    ratingValue: 4.6,
    reviewCount: 328,
  },
  {
    id: "fp-77",
    title: "Bose SoundLink Flex Portable Speaker White",
    priceValue: 118000,
    image: PRODUCT_IMAGES.speakerWhite,
    categoryId: "speakers",
    brandId: "bose",
    colorId: "white",
    screenInch: null,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    batteryHours: 12,
    weightGrams: 590,
    releaseYear: 2021,
    warrantyMonths: 12,
    mpn: "865983-0200",
    ratingValue: 4.6,
    reviewCount: 176,
  },
  {
    id: "fp-78",
    title: "Marshall Emberton II Portable Speaker Black",
    priceValue: 105000,
    image: PRODUCT_IMAGES.speakerRound,
    categoryId: "speakers",
    brandId: "marshall",
    colorId: "black",
    screenInch: null,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    batteryHours: 30,
    weightGrams: 700,
    releaseYear: 2022,
    warrantyMonths: 24,
    mpn: "1005895",
    ratingValue: 4.7,
    reviewCount: 233,
  },
  {
    id: "fp-79",
    title: "Apple HomePod mini Space Gray",
    priceValue: 89000,
    image: PRODUCT_IMAGES.speakerHome,
    categoryId: "speakers",
    brandId: "apple",
    colorId: "black",
    screenInch: null,
    refreshHz: null,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    batteryHours: null,
    weightGrams: 345,
    releaseYear: 2020,
    warrantyMonths: 12,
    mpn: "MY5G2",
    ratingValue: 4.5,
    reviewCount: 289,
  },
];
