import { PRODUCT_IMAGES } from "../productImages";

/** Tablets. See `productCatalog.js` for the shape and for why the ids are append-only. */
export const TABLETS = [
  {
    id: "fp-10",
    title: "Samsung Galaxy Tab S10 Ultra 256GB",
    priceValue: 585000,
    image: PRODUCT_IMAGES.tablet,
    categoryId: "tablets",
    brandId: "samsung",
    colorId: "grey",
    screenInch: 14.6,
    refreshHz: 120,
    storageGb: 256,
    ramGb: 12,
    batteryMah: 11200,
    weightGrams: 718,
    releaseYear: 2024,
    warrantyMonths: 24,
    mpn: "SM-X926B",
    ratingValue: 4.6,
    reviewCount: 178,
    homeSection: "variety",
  },
  {
    id: "fp-11",
    title: "Apple iPad Pro 13 M4 256GB Silver",
    priceValue: 715000,
    image: PRODUCT_IMAGES.tablet,
    categoryId: "tablets",
    brandId: "apple",
    colorId: "white",
    screenInch: 13,
    refreshHz: 120,
    storageGb: 256,
    ramGb: 8,
    batteryMah: 10000,
    weightGrams: 579,
    releaseYear: 2024,
    warrantyMonths: 12,
    mpn: "MVXW3",
    ratingValue: 4.9,
    reviewCount: 421,
  },
  {
    id: "fp-52",
    title: "Apple iPad Air 11 M2 128GB Blue",
    priceValue: 395000,
    image: PRODUCT_IMAGES.tabletPencil,
    categoryId: "tablets",
    brandId: "apple",
    colorId: "blue",
    screenInch: 11,
    refreshHz: 60,
    storageGb: 128,
    ramGb: 8,
    batteryMah: 7606,
    weightGrams: 462,
    releaseYear: 2024,
    warrantyMonths: 12,
    mpn: "MUWD3",
    ratingValue: 4.8,
    reviewCount: 356,
    homeSection: "top",
  },
  {
    id: "fp-53",
    title: "Apple iPad 11 128GB Starlight",
    priceValue: 245000,
    image: PRODUCT_IMAGES.tabletWhite,
    categoryId: "tablets",
    brandId: "apple",
    colorId: "beige",
    screenInch: 10.9,
    refreshHz: 60,
    storageGb: 128,
    ramGb: 6,
    batteryMah: 7606,
    weightGrams: 477,
    releaseYear: 2025,
    warrantyMonths: 12,
    mpn: "MXPP3",
    ratingValue: 4.7,
    reviewCount: 892,
  },
  {
    id: "fp-54",
    title: "Samsung Galaxy Tab S10 Plus 256GB Silver",
    priceValue: 425000,
    image: PRODUCT_IMAGES.tabletDesk,
    categoryId: "tablets",
    brandId: "samsung",
    colorId: "silver",
    screenInch: 12.4,
    refreshHz: 120,
    storageGb: 256,
    ramGb: 12,
    batteryMah: 10090,
    weightGrams: 571,
    releaseYear: 2024,
    warrantyMonths: 24,
    mpn: "SM-X828B",
    ratingValue: 4.5,
    reviewCount: 143,
  },
  {
    id: "fp-55",
    title: "Samsung Galaxy Tab A9+ 64GB Graphite",
    priceValue: 105000,
    image: PRODUCT_IMAGES.tabletBlack,
    categoryId: "tablets",
    brandId: "samsung",
    colorId: "grey",
    screenInch: 11,
    refreshHz: 90,
    storageGb: 64,
    ramGb: 4,
    batteryMah: 7040,
    weightGrams: 480,
    releaseYear: 2023,
    warrantyMonths: 24,
    mpn: "SM-X210",
    ratingValue: 4.3,
    reviewCount: 519,
  },
  {
    id: "fp-56",
    title: "Xiaomi Pad 7 128GB Slate Gray",
    priceValue: 195000,
    image: PRODUCT_IMAGES.tabletBlack,
    categoryId: "tablets",
    brandId: "xiaomi",
    colorId: "grey",
    screenInch: 11.2,
    refreshHz: 144,
    storageGb: 128,
    ramGb: 8,
    batteryMah: 8850,
    weightGrams: 500,
    releaseYear: 2024,
    warrantyMonths: 24,
    mpn: "24069PC21G",
    ratingValue: 4.4,
    reviewCount: 211,
  },
];
