import { PRODUCT_IMAGES } from "../productImages";

/**
 * TVs. See `productCatalog.js` for the shape and for why the ids are append-only.
 *
 * `panelType` is each TV's real panel technology, read by `buildSpecsForProduct`'s
 * extended screen-type row. It used to be a single literal, "Neo QLED 4K", shared by
 * every TV in the catalog regardless of brand — which is not a generic placeholder the
 * way "OLED" is on the laptop spec table, it is a Samsung trademark, so an LG or Sony
 * page was attributing a competitor's technology to itself.
 */
export const TVS = [
  {
    id: "fp-6",
    title: "Samsung Neo QLED 55-inch 4K Smart TV",
    priceValue: 525000,
    image: PRODUCT_IMAGES.tv,
    categoryId: "tv",
    brandId: "samsung",
    colorId: "black",
    panelType: "Neo QLED",
    screenInch: 55,
    refreshHz: 120,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    weightGrams: 16600,
    releaseYear: 2024,
    warrantyMonths: 24,
    mpn: "QN55QN90D",
    ratingValue: 4.7,
    reviewCount: 264,
    homeSection: "top",
  },
  {
    id: "fp-62",
    title: "LG OLED evo C4 65-inch 4K Smart TV",
    priceValue: 990000,
    image: PRODUCT_IMAGES.tvWall,
    categoryId: "tv",
    brandId: "lg",
    colorId: "black",
    panelType: "OLED",
    screenInch: 65,
    refreshHz: 144,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    weightGrams: 22400,
    releaseYear: 2024,
    warrantyMonths: 24,
    mpn: "OLED65C4",
    ratingValue: 4.8,
    reviewCount: 341,
    homeSection: "variety",
  },
  {
    id: "fp-63",
    title: "LG OLED evo C4 55-inch 4K Smart TV",
    priceValue: 720000,
    image: PRODUCT_IMAGES.tvStand,
    categoryId: "tv",
    brandId: "lg",
    colorId: "black",
    panelType: "OLED",
    screenInch: 55,
    refreshHz: 144,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    weightGrams: 17200,
    releaseYear: 2024,
    warrantyMonths: 24,
    mpn: "OLED55C4",
    ratingValue: 4.8,
    reviewCount: 512,
  },
  {
    id: "fp-64",
    title: "Samsung Crystal UHD 50-inch 4K Smart TV",
    priceValue: 295000,
    image: PRODUCT_IMAGES.tvCabinet,
    categoryId: "tv",
    brandId: "samsung",
    colorId: "black",
    panelType: "Crystal UHD",
    screenInch: 50,
    refreshHz: 60,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    weightGrams: 12300,
    releaseYear: 2024,
    warrantyMonths: 24,
    mpn: "UE50DU7100",
    ratingValue: 4.4,
    reviewCount: 618,
  },
  {
    id: "fp-65",
    title: "Sony BRAVIA 8 65-inch OLED 4K Smart TV",
    priceValue: 1150000,
    image: PRODUCT_IMAGES.tvLarge,
    categoryId: "tv",
    brandId: "sony",
    colorId: "black",
    panelType: "OLED",
    screenInch: 65,
    refreshHz: 120,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    weightGrams: 23100,
    releaseYear: 2024,
    warrantyMonths: 24,
    mpn: "K-65XR80",
    ratingValue: 4.7,
    reviewCount: 128,
  },
  {
    id: "fp-66",
    title: "TCL C755 55-inch Mini LED 4K Smart TV",
    priceValue: 385000,
    image: PRODUCT_IMAGES.tvPanelWall,
    categoryId: "tv",
    brandId: "tcl",
    colorId: "black",
    panelType: "Mini LED",
    screenInch: 55,
    refreshHz: 144,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    weightGrams: 15800,
    releaseYear: 2024,
    warrantyMonths: 24,
    mpn: "55C755",
    ratingValue: 4.5,
    reviewCount: 92,
  },
  {
    id: "fp-67",
    title: "Hisense U7N 65-inch Mini LED 4K Smart TV",
    priceValue: 545000,
    image: PRODUCT_IMAGES.tvBrickWall,
    categoryId: "tv",
    brandId: "hisense",
    colorId: "black",
    panelType: "Mini LED",
    screenInch: 65,
    refreshHz: 144,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    weightGrams: 19300,
    releaseYear: 2024,
    warrantyMonths: 24,
    mpn: "65U7N",
    ratingValue: 4.4,
    reviewCount: 76,
  },
  {
    id: "fp-68",
    title: "Philips 43-inch The One 4K Smart TV",
    priceValue: 235000,
    image: PRODUCT_IMAGES.tvSideboard,
    categoryId: "tv",
    brandId: "philips",
    colorId: "black",
    panelType: "LED",
    screenInch: 43,
    refreshHz: 60,
    storageGb: null,
    ramGb: null,
    batteryMah: null,
    weightGrams: 9600,
    releaseYear: 2023,
    warrantyMonths: 24,
    mpn: "43PUS8508",
    ratingValue: 4.3,
    reviewCount: 154,
  },
];
