import { PRODUCT_IMAGES } from "../productImages";

/** Wearables. See `productCatalog.js` for the shape and for why the ids are append-only. */
export const WEARABLES = [
  {
    id: "fp-13",
    title: "Apple Watch Ultra 2 Titanium",
    priceValue: 419000,
    image: PRODUCT_IMAGES.watch,
    categoryId: "wearables",
    brandId: "apple",
    colorId: "navy",
    screenInch: 1.9,
    refreshHz: null,
    storageGb: 64,
    ramGb: null,
    batteryMah: null,
    batteryHours: 80,
    weightGrams: 61,
    releaseYear: 2023,
    warrantyMonths: 12,
    mpn: "MREH3",
    ratingValue: 4.8,
    reviewCount: 512,
    homeSection: "variety",
  },
  {
    id: "fp-80",
    title: "Apple Watch Series 10 42mm Jet Black",
    priceValue: 245000,
    image: PRODUCT_IMAGES.watchBlack,
    categoryId: "wearables",
    brandId: "apple",
    colorId: "black",
    screenInch: 1.77,
    refreshHz: null,
    storageGb: 32,
    ramGb: null,
    batteryMah: null,
    batteryHours: 18,
    weightGrams: 34,
    releaseYear: 2024,
    warrantyMonths: 12,
    mpn: "MWWT3",
    ratingValue: 4.7,
    reviewCount: 743,
    homeSection: "top",
  },
  {
    id: "fp-81",
    title: "Samsung Galaxy Watch7 44mm Green",
    priceValue: 175000,
    image: PRODUCT_IMAGES.watchSport,
    categoryId: "wearables",
    brandId: "samsung",
    colorId: "green",
    screenInch: 1.5,
    refreshHz: null,
    storageGb: 32,
    ramGb: null,
    batteryMah: null,
    batteryHours: 40,
    weightGrams: 33,
    releaseYear: 2024,
    warrantyMonths: 24,
    mpn: "SM-L310",
    ratingValue: 4.5,
    reviewCount: 289,
  },
  {
    id: "fp-82",
    title: "Samsung Galaxy Watch Ultra 47mm Titanium White",
    priceValue: 355000,
    image: PRODUCT_IMAGES.watchWhite,
    categoryId: "wearables",
    brandId: "samsung",
    colorId: "white",
    screenInch: 1.5,
    refreshHz: null,
    storageGb: 32,
    ramGb: null,
    batteryMah: null,
    batteryHours: 60,
    weightGrams: 60,
    releaseYear: 2024,
    warrantyMonths: 24,
    mpn: "SM-L705",
    ratingValue: 4.6,
    reviewCount: 176,
  },
  {
    id: "fp-83",
    title: "Garmin Venu 3 45mm Slate Gray",
    priceValue: 265000,
    image: PRODUCT_IMAGES.watchFitness,
    categoryId: "wearables",
    brandId: "garmin",
    colorId: "grey",
    screenInch: 1.4,
    refreshHz: null,
    storageGb: 8,
    ramGb: null,
    batteryMah: null,
    batteryHours: 336,
    weightGrams: 47,
    releaseYear: 2023,
    warrantyMonths: 24,
    mpn: "010-02784-00",
    ratingValue: 4.7,
    reviewCount: 198,
  },
  {
    id: "fp-84",
    title: "Amazfit GTR 4 46mm Superspeed Black",
    priceValue: 95000,
    image: PRODUCT_IMAGES.watchAngled,
    categoryId: "wearables",
    brandId: "amazfit",
    colorId: "black",
    screenInch: 1.43,
    refreshHz: null,
    storageGb: 4,
    ramGb: null,
    batteryMah: null,
    batteryHours: 336,
    weightGrams: 34,
    releaseYear: 2023,
    warrantyMonths: 12,
    mpn: "A2166",
    ratingValue: 4.4,
    reviewCount: 231,
  },
];
