/**
 * Demo catalog products for the filter listing page (MVP).
 */

const DESC =
  "Choosy-ը նոր առցանց շուկա է՝ նախատեսված խելամիտ գնորդների և վաճառողների համար, ովքեր գնահատում են որակը։";

const IMG = {
  phone: "/assets/images/gridCatalog/smartphone.png",
  ear: "/assets/images/gridCatalog/earphones.png",
  bag: "/assets/images/gridCatalog/bag.png",
  lens: "/assets/images/gridCatalog/objective.png",
  nb: "/assets/images/gridCatalog/notebook.png",
};

/** @typedef {{ id: string, title: string, description: string, price: string, priceValue: number, image: string, href: string, screenInch: number, brandId: string, ramGb: number, colorId: string }} FilterCatalogProduct */

/** @type {FilterCatalogProduct[]} */
export const mockFilterProducts = [
  {
    id: "fp-1",
    title: "Apple iPhone 16 Pro Max 1TB Black Titanium",
    description: DESC,
    price: "489,600 AMD",
    priceValue: 489600,
    image: IMG.phone,
    href: "/singleproduct",
    screenInch: 13,
    brandId: "apple",
    ramGb: 8,
    colorId: "black",
  },
  {
    id: "fp-2",
    title: "Apple MacBook Pro 14",
    description: DESC,
    price: "1,200,000 AMD",
    priceValue: 1200000,
    image: IMG.nb,
    href: "/singleproduct",
    screenInch: 14,
    brandId: "apple",
    ramGb: 16,
    colorId: "grey",
  },
  {
    id: "fp-3",
    title: "SONY: Ականջակալներ",
    description: DESC,
    price: "120,600 AMD",
    priceValue: 120600,
    image: IMG.ear,
    href: "/singleproduct",
    screenInch: 11,
    brandId: "samsung",
    ramGb: 4,
    colorId: "white",
  },
  {
    id: "fp-4",
    title: "SLING: Պայուսակ",
    description: DESC,
    price: "120,600 AMD",
    priceValue: 120600,
    image: IMG.bag,
    href: "/singleproduct",
    screenInch: 12,
    brandId: "samsung",
    ramGb: 8,
    colorId: "navy",
  },
  {
    id: "fp-5",
    title: "Sigma 30mm f/1.4 Contemporary DC DN",
    description: DESC,
    price: "120,600 AMD",
    priceValue: 120600,
    image: IMG.lens,
    href: "/singleproduct",
    screenInch: 12,
    brandId: "hp",
    ramGb: 8,
    colorId: "black",
  },
  {
    id: "fp-6",
    title: "Sony 4K TV",
    description: DESC,
    price: "450,000 AMD",
    priceValue: 450000,
    image: IMG.bag,
    href: "/singleproduct",
    screenInch: 15,
    brandId: "samsung",
    ramGb: 16,
    colorId: "black",
  },
  {
    id: "fp-7",
    title: "Նոթբուքեր — Dell XPS 15",
    description: DESC,
    price: "980,000 AMD",
    priceValue: 980000,
    image: IMG.nb,
    href: "/singleproduct",
    screenInch: 15,
    brandId: "dell",
    ramGb: 32,
    colorId: "navy",
  },
  {
    id: "fp-8",
    title: "HP Pavilion 15",
    description: DESC,
    price: "560,000 AMD",
    priceValue: 560000,
    image: IMG.nb,
    href: "/singleproduct",
    screenInch: 15,
    brandId: "hp",
    ramGb: 8,
    colorId: "grey",
  },
  {
    id: "fp-9",
    title: "Lenovo ThinkPad X1",
    description: DESC,
    price: "1,050,000 AMD",
    priceValue: 1050000,
    image: IMG.nb,
    href: "/singleproduct",
    screenInch: 14,
    brandId: "lenovo",
    ramGb: 16,
    colorId: "black",
  },
  {
    id: "fp-10",
    title: "Samsung Galaxy Tab S9",
    description: DESC,
    price: "380,000 AMD",
    priceValue: 380000,
    image: IMG.phone,
    href: "/singleproduct",
    screenInch: 11,
    brandId: "samsung",
    ramGb: 128,
    colorId: "grey",
  },
  {
    id: "fp-11",
    title: "Apple iPad Pro 12.9",
    description: DESC,
    price: "890,000 AMD",
    priceValue: 890000,
    image: IMG.phone,
    href: "/singleproduct",
    screenInch: 13,
    brandId: "apple",
    ramGb: 16,
    colorId: "white",
  },
  {
    id: "fp-12",
    title: "Dell Inspiron 14",
    description: DESC,
    price: "420,000 AMD",
    priceValue: 420000,
    image: IMG.nb,
    href: "/singleproduct",
    screenInch: 14,
    brandId: "dell",
    ramGb: 8,
    colorId: "grey",
  },
  {
    id: "fp-13",
    title: "HP EliteBook 13",
    description: DESC,
    price: "720,000 AMD",
    priceValue: 720000,
    image: IMG.nb,
    href: "/singleproduct",
    screenInch: 13,
    brandId: "hp",
    ramGb: 16,
    colorId: "navy",
  },
  {
    id: "fp-14",
    title: "Lenovo IdeaPad 15",
    description: DESC,
    price: "310,000 AMD",
    priceValue: 310000,
    image: IMG.nb,
    href: "/singleproduct",
    screenInch: 15,
    brandId: "lenovo",
    ramGb: 4,
    colorId: "white",
  },
  {
    id: "fp-15",
    title: "Samsung Galaxy Book 12",
    description: DESC,
    price: "640,000 AMD",
    priceValue: 640000,
    image: IMG.nb,
    href: "/singleproduct",
    screenInch: 12,
    brandId: "samsung",
    ramGb: 8,
    colorId: "black",
  },
  {
    id: "fp-16",
    title: "Apple MacBook Air 13",
    description: DESC,
    price: "950,000 AMD",
    priceValue: 950000,
    image: IMG.nb,
    href: "/singleproduct",
    screenInch: 13,
    brandId: "apple",
    ramGb: 8,
    colorId: "grey",
  },
  {
    id: "fp-17",
    title: "Dell Latitude 14",
    description: DESC,
    price: "580,000 AMD",
    priceValue: 580000,
    image: IMG.nb,
    href: "/singleproduct",
    screenInch: 14,
    brandId: "dell",
    ramGb: 16,
    colorId: "black",
  },
  {
    id: "fp-18",
    title: "HP Spectre x360 13",
    description: DESC,
    price: "1,100,000 AMD",
    priceValue: 1100000,
    image: IMG.nb,
    href: "/singleproduct",
    screenInch: 13,
    brandId: "hp",
    ramGb: 32,
    colorId: "navy",
  },
  {
    id: "fp-19",
    title: "Lenovo Yoga 11",
    description: DESC,
    price: "410,000 AMD",
    priceValue: 410000,
    image: IMG.nb,
    href: "/singleproduct",
    screenInch: 11,
    brandId: "lenovo",
    ramGb: 8,
    colorId: "grey",
  },
  {
    id: "fp-20",
    title: "Samsung Notebook 15",
    description: DESC,
    price: "520,000 AMD",
    priceValue: 520000,
    image: IMG.nb,
    href: "/singleproduct",
    screenInch: 15,
    brandId: "samsung",
    ramGb: 16,
    colorId: "white",
  },
  {
    id: "fp-21",
    title: "Apple Watch Ultra",
    description: DESC,
    price: "380,000 AMD",
    priceValue: 380000,
    image: IMG.phone,
    href: "/singleproduct",
    screenInch: 12,
    brandId: "apple",
    ramGb: 4,
    colorId: "navy",
  },
  {
    id: "fp-22",
    title: "Dell Precision 15",
    description: DESC,
    price: "1,350,000 AMD",
    priceValue: 1350000,
    image: IMG.nb,
    href: "/singleproduct",
    screenInch: 15,
    brandId: "dell",
    ramGb: 32,
    colorId: "black",
  },
  {
    id: "fp-23",
    title: "HP Chromebook 14",
    description: DESC,
    price: "180,000 AMD",
    priceValue: 180000,
    image: IMG.nb,
    href: "/singleproduct",
    screenInch: 14,
    brandId: "hp",
    ramGb: 4,
    colorId: "grey",
  },
  {
    id: "fp-24",
    title: "Lenovo Legion 15",
    description: DESC,
    price: "890,000 AMD",
    priceValue: 890000,
    image: IMG.nb,
    href: "/singleproduct",
    screenInch: 15,
    brandId: "lenovo",
    ramGb: 16,
    colorId: "black",
  },
];
