/**
 * Demo catalog products for the filter listing page (MVP).
 */

import { getProductDetailHref } from "entities/product-detail/model/productRouteRegistry";

const DESC =
  "Carefully selected tech product with verified specifications, clear pricing, and marketplace-ready details.";

/** High-quality display crop; ProgressiveImage derives a tiny preview automatically. */
const IMG_CROP = "auto=format&fit=crop&w=1200&h=900&q=85";

const IMG = {
  iphoneOrange: `https://images.unsplash.com/photo-1592750475338-74b7b21085ab?${IMG_CROP}`,
  iphoneBlack: `https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?${IMG_CROP}`,
  samsungPhone: `https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?${IMG_CROP}`,
  headphones: `https://images.unsplash.com/photo-1505740420928-5e560c06d30e?${IMG_CROP}`,
  earbuds: `https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?${IMG_CROP}`,
  watch: `https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?${IMG_CROP}`,
  lens: `https://images.unsplash.com/photo-1502920917128-1aa500764cbd?${IMG_CROP}`,
  macbook: `https://images.unsplash.com/photo-1517336714731-489689fd1ca8?${IMG_CROP}`,
  laptop: `https://images.unsplash.com/photo-1496181133206-80ce9b88a853?${IMG_CROP}`,
  tablet: `https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?${IMG_CROP}`,
  tv: `https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?${IMG_CROP}`,
  gamingLaptop: `https://images.unsplash.com/photo-1593642632823-8f785ba67e45?${IMG_CROP}`,
};

/** @typedef {{ id: string, title: string, description: string, price: string, priceValue: number, image: string, href: string, categoryId: string, screenInch: number, brandId: string, ramGb: number, colorId: string }} FilterCatalogProduct */

const CATEGORY_BY_PRODUCT_ID = {
  "fp-1": "smartphones",
  "fp-2": "laptops",
  "fp-3": "speakers",
  "fp-4": "smartphones",
  "fp-5": "cameras",
  "fp-6": "tv",
  "fp-7": "laptops",
  "fp-8": "laptops",
  "fp-9": "laptops",
  "fp-10": "tablets",
  "fp-11": "tablets",
  "fp-12": "headphones",
  "fp-13": "wearables",
  "fp-14": "laptops",
  "fp-15": "laptops",
  "fp-16": "smartphones",
  "fp-17": "laptops",
  "fp-18": "laptops",
  "fp-19": "laptops",
  "fp-20": "smartphones",
  "fp-21": "headphones",
  "fp-22": "laptops",
  "fp-23": "laptops",
  "fp-24": "laptops",
};

export const mockFilterProductsBase = [
  {
    id: "fp-1",
    title: "Apple iPhone 17 Pro Max 256GB Cosmic Orange",
    description: DESC,
    price: "739,000 AMD",
    priceValue: 739000,
    image: IMG.iphoneOrange,
    screenInch: 13,
    brandId: "apple",
    ramGb: 8,
    colorId: "orange",
  },
  {
    id: "fp-2",
    title: "Apple MacBook Pro 14 M4 Pro 512GB Space Black",
    description: DESC,
    price: "1,290,000 AMD",
    priceValue: 1290000,
    image: IMG.macbook,
    screenInch: 14,
    brandId: "apple",
    ramGb: 16,
    colorId: "black",
  },
  {
    id: "fp-3",
    title: "Sony WH-1000XM5 Wireless Headphones",
    description: DESC,
    price: "165,000 AMD",
    priceValue: 165000,
    image: IMG.headphones,
    screenInch: 11,
    brandId: "sony",
    ramGb: 4,
    colorId: "white",
  },
  {
    id: "fp-4",
    title: "Samsung Galaxy S25 Ultra 512GB Titanium Black",
    description: DESC,
    price: "615,000 AMD",
    priceValue: 615000,
    image: IMG.samsungPhone,
    screenInch: 12,
    brandId: "samsung",
    ramGb: 12,
    colorId: "black",
  },
  {
    id: "fp-5",
    title: "Sigma 30mm f/1.4 Contemporary DC DN",
    description: DESC,
    price: "185,000 AMD",
    priceValue: 185000,
    image: IMG.lens,
    screenInch: 12,
    brandId: "sony",
    ramGb: 8,
    colorId: "black",
  },
  {
    id: "fp-6",
    title: "Samsung Neo QLED 55-inch 4K Smart TV",
    description: DESC,
    price: "525,000 AMD",
    priceValue: 525000,
    image: IMG.tv,
    screenInch: 15,
    brandId: "samsung",
    ramGb: 16,
    colorId: "black",
  },
  {
    id: "fp-7",
    title: "Dell XPS 15 OLED 1TB Silver",
    description: DESC,
    price: "1,080,000 AMD",
    priceValue: 1080000,
    image: IMG.laptop,
    screenInch: 15,
    brandId: "dell",
    ramGb: 32,
    colorId: "grey",
  },
  {
    id: "fp-8",
    title: "HP Spectre x360 14 OLED",
    description: DESC,
    price: "760,000 AMD",
    priceValue: 760000,
    image: IMG.laptop,
    screenInch: 14,
    brandId: "hp",
    ramGb: 16,
    colorId: "navy",
  },
  {
    id: "fp-9",
    title: "Lenovo ThinkPad X1 Carbon Gen 12",
    description: DESC,
    price: "950,000 AMD",
    priceValue: 950000,
    image: IMG.laptop,
    screenInch: 14,
    brandId: "lenovo",
    ramGb: 16,
    colorId: "black",
  },
  {
    id: "fp-10",
    title: "Samsung Galaxy Tab S10 Ultra 256GB",
    description: DESC,
    price: "585,000 AMD",
    priceValue: 585000,
    image: IMG.tablet,
    screenInch: 14,
    brandId: "samsung",
    ramGb: 128,
    colorId: "grey",
  },
  {
    id: "fp-11",
    title: "Apple iPad Pro 13 M4 256GB Silver",
    description: DESC,
    price: "715,000 AMD",
    priceValue: 715000,
    image: IMG.tablet,
    screenInch: 13,
    brandId: "apple",
    ramGb: 16,
    colorId: "white",
  },
  {
    id: "fp-12",
    title: "Apple AirPods Pro 2 USB-C",
    description: DESC,
    price: "129,000 AMD",
    priceValue: 129000,
    image: IMG.earbuds,
    screenInch: 11,
    brandId: "apple",
    ramGb: 4,
    colorId: "white",
  },
  {
    id: "fp-13",
    title: "Apple Watch Ultra 2 Titanium",
    description: DESC,
    price: "419,000 AMD",
    priceValue: 419000,
    image: IMG.watch,
    screenInch: 12,
    brandId: "apple",
    ramGb: 4,
    colorId: "navy",
  },
  {
    id: "fp-14",
    title: "Apple MacBook Air 13 M3 256GB Midnight",
    description: DESC,
    price: "690,000 AMD",
    priceValue: 690000,
    image: IMG.macbook,
    screenInch: 13,
    brandId: "apple",
    ramGb: 8,
    colorId: "black",
  },
  {
    id: "fp-15",
    title: "Samsung Galaxy Book4 Pro 16",
    description: DESC,
    price: "880,000 AMD",
    priceValue: 880000,
    image: IMG.laptop,
    screenInch: 16,
    brandId: "samsung",
    ramGb: 16,
    colorId: "black",
  },
  {
    id: "fp-16",
    title: "Apple iPhone 16 128GB Ultramarine",
    description: DESC,
    price: "445,000 AMD",
    priceValue: 445000,
    image: IMG.iphoneBlack,
    screenInch: 13,
    brandId: "apple",
    ramGb: 8,
    colorId: "blue",
  },
  {
    id: "fp-17",
    title: "Dell Latitude 7450 Business Laptop",
    description: DESC,
    price: "640,000 AMD",
    priceValue: 640000,
    image: IMG.laptop,
    screenInch: 14,
    brandId: "dell",
    ramGb: 16,
    colorId: "black",
  },
  {
    id: "fp-18",
    title: "HP Omen 16 RTX Gaming Laptop",
    description: DESC,
    price: "820,000 AMD",
    priceValue: 820000,
    image: IMG.gamingLaptop,
    screenInch: 16,
    brandId: "hp",
    ramGb: 32,
    colorId: "black",
  },
  {
    id: "fp-19",
    title: "Lenovo Yoga Slim 7 14 OLED",
    description: DESC,
    price: "590,000 AMD",
    priceValue: 590000,
    image: IMG.laptop,
    screenInch: 14,
    brandId: "lenovo",
    ramGb: 16,
    colorId: "grey",
  },
  {
    id: "fp-20",
    title: "Samsung Galaxy S24 FE 256GB Graphite",
    description: DESC,
    price: "335,000 AMD",
    priceValue: 335000,
    image: IMG.samsungPhone,
    screenInch: 15,
    brandId: "samsung",
    ramGb: 8,
    colorId: "black",
  },
  {
    id: "fp-21",
    title: "Sony WF-1000XM5 Wireless Earbuds",
    description: DESC,
    price: "118,000 AMD",
    priceValue: 118000,
    image: IMG.earbuds,
    screenInch: 11,
    brandId: "sony",
    ramGb: 4,
    colorId: "black",
  },
  {
    id: "fp-22",
    title: "Dell Precision 5690 Workstation",
    description: DESC,
    price: "1,420,000 AMD",
    priceValue: 1420000,
    image: IMG.laptop,
    screenInch: 16,
    brandId: "dell",
    ramGb: 32,
    colorId: "black",
  },
  {
    id: "fp-23",
    title: "HP Chromebook Plus 14",
    description: DESC,
    price: "245,000 AMD",
    priceValue: 245000,
    image: IMG.laptop,
    screenInch: 14,
    brandId: "hp",
    ramGb: 8,
    colorId: "grey",
  },
  {
    id: "fp-24",
    title: "Lenovo Legion 15",
    description: DESC,
    price: "890,000 AMD",
    priceValue: 890000,
    image: IMG.gamingLaptop,
    screenInch: 15,
    brandId: "lenovo",
    ramGb: 16,
    colorId: "black",
  },
];

/** @type {FilterCatalogProduct[]} */
export const mockFilterProducts = mockFilterProductsBase.map((p) => ({
  ...p,
  categoryId: CATEGORY_BY_PRODUCT_ID[p.id] ?? "smartphones",
  href: getProductDetailHref(p.id, p.title),
}));
